% Fast Transient Sensors - Coursework 1
% Devon Kerai (B128203)
% Due 14th January 2015

% Question 6

% Variables
mew = 4*pi*10^-7;
epsillion = 8.854*10^-12;
length = 8; % meters
diameter = 0.10*10^-3; % meters of conducter/core
radius = diameter / 2;
thickness = 0.02*10^-3; % meters
Lm = 100*10^-3; % meters (length of mandrel)
dm = 4*10^-3; % meters (diameter of mandrel)
rm = dm/2; % meters (radius of mandrel)
lengthextracoil= 10*10^-3; % meters (length of extra coil)
permittivity = 2.3;
row = 1.72*10^-8; % electrical resistivity of copper


% Part A
area = pi*(radius^2)
resistance = (row*length) / (area); % 17.5198 = 17.52Ohms

% Part B
totalradius = rm + thickness; % 0.004
pitchnum = (Lm^2) * ((2*pi*totalradius)^2);
pitchdenom = ((length - (2*lengthextracoil))^2) - (Lm^2);

pitchtotal = sqrt(pitchnum/pitchdenom); % 1.591*10^-4 meters
turns = Lm / pitchtotal; % 628.6914 = 628.7 turns

correctionFactor = Lm/(Lm+(0.9*totalradius));
inductance = ((mew*pi*(turns^2)*(totalradius^2))/(Lm))*correctionFactor; % 6.2534*10^-5 = 62.53uH

% Part C

% Estimate equation
Fdenum1 = (1+(thickness/radius))^((permittivity-1)/permittivity);
F = pitchtotal/(2*radius*Fdenum1); % 1.315

ctop = 2*(pi^2)*epsillion*totalradius; % 3.5304*10^-13
cbot_1 = (1+(thickness/radius))^(2/permittivity);
cbot = log(F+sqrt((F^2)-cbot_1)); % 0.6624
captotal = (ctop/cbot)*turns; % 3.3509*10^-10 = 0.34nF


% Part D
Crectnum = pi*epsillion*lengthextracoil % 2.7816*10^-13
Crectdenom = log((Lm-(2*(radius+thickness)))/radius);
Crect = Crectnum/Crectdenom; % 3.6602X10^-14 = 366pF

% a = Lm, b = lengthextracoil
d = sqrt(Lm^2+lengthextracoil^2); % 0.1005
l = 2*(Lm+lengthextracoil); % 0.22
firstbit = mew/pi; % 4*10^-7
secondbit = Lm*(log((2*Lm*lengthextracoil)/(radius*(Lm+d)))); % 0.5296
thirdbit = lengthextracoil*(log((2*Lm*lengthextracoil)/(radius*(lengthextracoil+d)))); % 0.0589
fourthbit = (2*d)-(l*(7/8)); % 0.0085
Lrect = firstbit*(secondbit+thirdbit+fourthbit); % 2.3880*10^-7 = 0.24uH

% Part E
Ltotal = inductance + Lrect; % 6.2772*10^-5 = 62uH
Ctotal = captotal + Crect; % 3.3513*10^-10 = 0.34nF
resfreq = 1/(2*pi*sqrt(Ltotal*Ctotal)) % resonant frequency = 1.0973*10^6 = 1.1MHz

% Part F
freq = (1*10^5:1000:1*10^9);

w = 2*pi*freq;
s = 1i.*w;
L = inductance;
C = captotal;
R = resistance;

Znum = 1+((s.*L)./R);
Zdenom = 1+((s.^2).*L.*C)+(s.*R.*C);
z = R*(Znum./Zdenom);
loglog (freq, z)
grid on
grid minor
title ('Plot to show the magnetic flux density generated by one coil along its axis')
xlabel ('Freq (Hz)')
ylabel ('Impedance (Ohms)')


